name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-unity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build Server
        run: dotnet publish -c Release
      # Hier könntest du einen Deployment-Schritt einfügen
